export { default as Home } from "../Home";
export { default as Action } from "../ActionGenre.jsx";
export { default as Adventure } from "../AdventureGenre";
export { default as Romance } from "../RomanceGenre";
export { default as Fiction } from "../FictionGenre";
export { default as Horror } from "../HorrorGenre";
export { default as MyBookshelf } from "../MyBookshelf";
export { default as UploadBook } from "../UploadBookForm";
export { default as UploadImg } from "../UploadImageForm";